### PR TITLE
ensure categories are tuple

### PR DESCRIPTION
**Pull request by ccomb**
Simple fix for #212

### CODE REVIEW

**Comment by cmutel** [comment]
I think we also then need to convert to a tuple in line 316 as well. We also need a quick test to make sure we don't get a regression in the future.

**Comment by cmutel** [comment]
@ccomb Ping ;p

**Comment by ccomb** [comment]
ACK, still alive ;-)

**Comment by ccomb** [comment]
I added a simple test that reproduces the traceback if there is no tuple conversion

**Pull request merged**
