### PR TITLE
Missing attribute during import (fixes #196)

### LINKED ISSUE #196: Missing ecospold2 attributes: includedActivitiesStart includedActivitiesEnd
During import of Ecoinvent on spold2 format, we're missing two attributes that should end up in the comments :
- includedActivitiesStart
- includedActivitiesEnd

```
      <activity specialActivityType="0" id="17c3ea39-c90d-52f8-b222-36b2d0d19cb2" activityNameId="ffadd8a1-f004-464b-adc9-4830de080166" parentActivityId="c64a4c3c-ee75-4b16-a06a-baada6d79800" inheritanceDepth="-1" type="1">
        <activityName xml:lang="en">textile production, cotton, air jet loom weaving</activityName>
        <includedActivitiesStart xml:lang="en">The activity starts with warping and sizing of cotton yarn.</includedActivitiesStart>
        <includedActivitiesEnd xml:lang="en">This process ends with conversion of cotton yarn at weaving plant to 1 kg of woven fabric.</includedActivitiesEnd>
```
The code does:
```
>>> stem.activityDescription.activity.includedActivitiesStart.get("text")
>>> 
```

we can read it with:
```
>>> stem.activityDescription.activity.includedActivitiesStart
"This activity starts at the gate of the activities that produce 'celery',  within the geography of Global."
```

### PR DESCRIPTION
**Pull request by ccomb**
fixes #196

### CODE REVIEW

**Comment by cmutel** [comment]
Hey, this is awesome but definitely needs a test.

**Comment by cmutel** [comment]
@ccomb Ready to merge if we get a test

**Comment by ccomb** [comment]
Sure, sorry, I'll try to find a moment this week !

**Comment by ccomb** [comment]
Added a test ! (and fixed a conversion bug for comments)

**Pull request merged**
