### PR TITLE
Fixed all test errors

### PR DESCRIPTION
**Pull request by BenPortner**
- Removed "encoding" keyword from csv.reader initialization. 
- use newline='' when writing to csv file to prevent duplicate newlines
- use lca.dicts.product/activity instead of lca.product_dict/activity_dict

No errors when running pytest on my machine. I assume all error are fixed.

### CODE REVIEW

**Review by cmutel — CHANGES_REQUESTED** [review]
Can you rebase to the latest code? I don't think the changes to `data/__init__.py` are needed anymore, but you can still wrap the reader in a context manager.

**Comment by BenPortner** [comment]
(nevermind, checked the wrong `__init__.py`)

**Comment by BenPortner** [comment]
@cmutel: should be fixed!

**Comment by cmutel** [comment]
Not sure this fixes **all** test errors, but it is a good start :)

**Comment by BenPortner** [comment]
Let me know if you find more errors 😅

**Pull request merged**
